import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" className="min-h-screen">
        <body className="bg-main-foreground flex flex-col min-h-screen overflow-x-hidden">
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
